name: CI/CD

on:
  pull_request:
    branches: [develop]

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Type checking
        run: bun tsc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint code
        run: bun check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: bun run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [type-check, lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build project
        run: bun run build
  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [type-check, lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install Cypress
        run: bun cypress:install
      - name: Run E2E tests
        run: bun e2e
